CREATE TABLE IF NOT EXISTS app_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    event_type ENUM('OPEN', 'CLOSE') NOT NULL,
    ts DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS app_sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    opened_at DOUBLE NOT NULL,
    closed_at DOUBLE,
    duration DOUBLE,
    opened_dt DATETIME GENERATED ALWAYS AS (FROM_UNIXTIME(opened_at)) STORED
);

